### ISSUE TITLE
Problem with label Caddy Proxy

### ISSUE THREAD

**Issue by yuandrk** [yuandrk/Docker-Raspberry-PI-Stack#2]
When deploying Docker Compose, Caddy does not set up config file correctly 

```
 labels:
      caddy: grafana.yuandrk.net
      caddy.reverse_proxy: "{{upstreams 3000}}"
      caddy.header: /*
```

result: 
``` 
grafana.yuandrk.net {
	header /*
	reverse_proxy 
}
````
